In [ ]:
!pip install gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import gym
import time
from IPython.display import clear_output
import random

In [ ]:
env=gym.make("FrozenLake-v1")

In [ ]:
action_space_size=env.action_space.n # columns
state_space_size=env.observation_space.n # rows

q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes=10000 # total number of episodes to play during training
max_steps_per_episode=100 # maximum step to take within single episode

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [ ]:
rewards_all_episodes=[]
## Q-learning algorithm
# what happen in single episode:
for episode in range(num_episodes):
    state=env.reset() # reset for each new episode
    done=False # keep track whether or not the episode finish, start=False
    rewards_current_episode=0 # track reward, start=0
    # what happen in each step of episode:
    for step in range(max_steps_per_episode):
        # Exploration & exploitation trade off
        exploration_rate_threshold=random.uniform(0,1) # create random number (r) at each time step
        if exploration_rate_threshold > exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
            
        new_state,reward,done,info=env.step(action)# apply action & get results
        
        #Update Q-table:
        q_table[state,action]=q_table[state,action]*(1-learning_rate) + \
        learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state=new_state
        rewards_current_episode+=reward
        
        if done==True:
            break
    # Exploration rate decay
    exploration_rate=min_exploration_rate+\
    (max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)

In [ ]:
# Calculate and print average reward per thousand episodes
rewards_per_thousand_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
    print(count,':',str(sum(r/1000)))
    count+=1000

#Print update Q table
print('\n\nQ-table\n')
print(q_table)

Average reward per thousand episodes

1000 : 0.04300000000000003
2000 : 0.22300000000000017
3000 : 0.4100000000000003
4000 : 0.5520000000000004
5000 : 0.6420000000000005
6000 : 0.6900000000000005
7000 : 0.6660000000000005
8000 : 0.7110000000000005
9000 : 0.6600000000000005
10000 : 0.6800000000000005


Q-table

[[0.52014459 0.48141041 0.47639641 0.48190952]
 [0.24573569 0.28467066 0.32497345 0.47021687]
 [0.42582832 0.41799867 0.40257151 0.4398834 ]
 [0.25148924 0.18915962 0.33943434 0.42777979]
 [0.54097572 0.2458842  0.34278903 0.36862783]
 [0.         0.         0.         0.        ]
 [0.15981744 0.16653198 0.2739735  0.15429286]
 [0.         0.         0.         0.        ]
 [0.43884179 0.26834363 0.31398568 0.56464713]
 [0.44145192 0.61916438 0.4031545  0.41525321]
 [0.50670688 0.42389761 0.36826324 0.33044433]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.47518972 0.60851627 0.75593838 0.51700725]
 [0.77146825 0.90287045 0.7887

In [ ]:
      
# see the agent actual play
for episode in range(3):
  state=env.reset()
  done=False
  print("Episode",episode+1,"\n")
  time.sleep(1) 

  for step in range (max_steps_per_episode):
    clear_output(wait=True)# clear output for another output printout,for visual smoothness
    print(env.render(mode="ansi")) #see where agent on the grid
    time.sleep(0.3)

    action=np.argmax(q_table[state,:])
    new_state,reward,done,info=env.step(action)

    if done:
      clear_output(wait=True)
      print(env.render(mode="ansi"))
      if reward==1:
        print('Win')
        time.sleep(3)
      else:
        print('Fell hole')
        time.sleep(3)
      clear_output(wait=True)
      break

    state=new_state # if  the last action do not complete the episode, then skip the conditional, move to new state &  next time step
env.close() # close the environment
      

  (Down)
SFFF
FHFH
FFFH
HFFG

Win
